---
- hosts: local 
  tasks:
  - name: install shade 
    pip: 
     name: shade
  - name: get some facts and then print them   
    os_server_facts:
      server: "*" 
  - name: register variable 
    debug: 
      var: openstack_servers
  - name: print stuff 
    debug: 
      msg: "{{ openstack_servers[1].name}}"

  - name: allocate floating IP to named VM 
    os_floating_ip: 
      server: "{{ item.name }}" 
    with_items: 
    - "{{ openstack_servers }}" 
